name: Auto Trigger FMT

on:
  workflow_dispatch:
    inputs:
      fixture:
        description: 'Fixture to predict (e.g., Athletic Bilbao vs Manchester United)'
        required: true
        type: string

jobs:
  run_fmt_prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Inject FMT Request into fmt-state.json
        run: |
          FIXTURE="${{ github.event.inputs.fixture }}"
          TEAM_A=$(echo "$FIXTURE" | cut -d'v' -f1 | xargs)
          TEAM_B=$(echo "$FIXTURE" | cut -d'v' -f2 | xargs)
          DATE=$(date -u +"%Y-%m-%d")

          echo "Injecting: $TEAM_A vs $TEAM_B on $DATE"

          jq --arg a "$TEAM_A" --arg b "$TEAM_B" --arg d "$DATE" \
            '.pending_fmt_request = { "team_a": $a, "team_b": $b, "date": $d }' fmt-state.json > tmp.json && mv tmp.json fmt-state.json

      - name: Commit & Push Updated fmt-state.json
        run: |
          git config user.name "fmt-bot"
          git config user.email "fmt-bot@users.noreply.github.com"
          git add fmt-state.json
          git commit -m "📥 New pending_fmt_request: ${{ github.event.inputs.fixture }}"
          git push https://x-access-token:${{ secrets.PAT_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
