trigger:
  source: fmt-results-ranker.yml
  expects:
    - top_5_predictions
    - full_predictions
    - context
    - target_file

action:
  type: write_to_json
  isolate: true
  force: true
  tag: FMT_CORE_CHAIN
  config:
    file: "{{ target_file }}"
    fields:
      predictions:
        top_5: "{{ top_5_predictions }}"
        all: "{{ full_predictions }}"
        fixture_context: "{{ context }}"
        timestamp: "{{ now_utc }}"

on_success:
  pass_to: fmt-predict-log.yml
  payload:
    full_predictions: "{{ full_predictions }}"
    context: "{{ context }}"

on_fail:
  message: "❌ Failed to write predictions to history log. Check downstream configuration."
