trigger:
  source: fmt-results-ranker.yml
  expects:
    - top_5_predictions
    - full_predictions
    - context

action:
  type: save_predictions_to_json
  isolate: true
  force: true
  tag: FMT_CORE_CHAIN
  config:
    output_file: fmt-history.json
    overwrite_fields:
      predictions:
        top_5: "{{ top_5_predictions }}"
        all: "{{ full_predictions }}"
        fixture_context: "{{ context }}"
        timestamp: "{{ now }}"

on_success:
  message: |
    ✅ FMT prediction complete.
    Showing Top 5 predictions (ranked by probability).
    🔽 Use “Show All Predictions” to expand full market view.

on_fail:
  message: "Saving predictions failed. Please retry or escalate to a system developer."
