name: Auto Trigger FMT

on:
  workflow_dispatch:
    inputs:
      fixture:
        description: 'Fixture to predict (e.g., Arsenal vs PSG)'
        required: true
        type: string

jobs:
  run_fmt_prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create FMT Request JSON
        run: |
          echo "{\"fixture\": \"${{ github.event.inputs.fixture }}\", \"scan_all_markets\": true}" > fmt-request.json

      - name: Commit FMT Request
        run: |
          git config user.name "fmt-bot"
          git config user.email "fmt-bot@users.noreply.github.com"
          git add fmt-request.json
          git commit -m "New FMT Request: ${{ github.event.inputs.fixture }}"
          git push
