name: Auto Trigger FMT

on:
  workflow_dispatch:
    inputs:
      fixture:
        description: 'Fixture to predict (e.g., Napoli vs Torino)'
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  run_fmt_prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Trigger FMT Prediction
        run: |
          echo "Invoking VD-36 (FMT Prediction Executor)"
          echo "{\"fixture\": \"${{ github.event.inputs.fixture }}\", \"scan_all_markets\": true}" > fmt-request.json

      - name: Commit and Push FMT Request
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fmt-request.json
          git commit -m "New FMT Request: ${{ github.event.inputs.fixture }}" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git || echo "Nothing to push"
