name: Impact Promoter

on:
  workflow_dispatch:

jobs:
  promote_enhancement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set Impact Ready to True
        run: |
          jq '.enhancement_status.impact_ready = true' fmt-state.json > tmp.json && mv tmp.json fmt-state.json

      - name: Commit and Push with Force
        run: |
          git config user.name "fmt-bot"
          git config user.email "bot@fmt.dev"
          git add fmt-state.json
          git commit -m "Impact Promoter: Marked PE-P1 as ready"
          git push --force https://x-access-token:${{ secrets.PAT_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
