name: FMT Launch Impact Promoter Phase 2

on:
  workflow_dispatch:

jobs:
  launch_impact_promoter_phase2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Initialize Impact Promoter Phase 2
        run: |
          # Create or update dev_phases block
          jq '.dev_phases = (.dev_phases // {})' fmt-core-state.json > tmp.json && mv tmp.json fmt-core-state.json

          # Add or update the phase entry
          jq --arg id "IP-P2" \
             --arg title "Impact Promoter – Phase 2" \
             --argjson vds '["VD-17","VD-18"]' \
             '.dev_phases[$id] = {
                "title": $title,
                "vds_assigned": $vds,
                "status": "In Progress",
                "progress": "0%",
                "eta": "6h",
                "complete": false
              }' fmt-core-state.json > tmp.json && mv tmp.json fmt-core-state.json

          # Protect assigned VDs
          for vd in VD-17 VD-18; do
            jq --arg id "$vd" '.vds[$id].protected = true' fmt-core-state.json > tmp.json && mv tmp.json fmt-core-state.json
          done

      - name: Commit and Push Changes
        run: |
          git config user.name "fmt-bot"
          git config user.email "bot@fmt.dev"
          git add fmt-core-state.json
          git diff --cached --quiet || git commit -m "Launch Impact Promoter Phase 2"
          git push https://x-access-token:${{ secrets.PAT_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
