name: FMT Prediction Enhancer Tracker

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  track_enhancer_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Calculate Enhancer Progress
        run: |
          echo "Checking prediction enhancer VDs (VD-11 to VD-16)..."
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          total=6
          active_count=$(jq '[.vds["VD-11","VD-12","VD-13","VD-14","VD-15","VD-16"] | select(.status == "Active")] | length' fmt-core-state.json)
          percent=$(awk "BEGIN { printf \"%.0f\", ($active_count / $total) * 100 }")

          jq --arg ts "$TS" \
             --arg percent "$percent%" \
             '.enhancement_status = {
                "phase": "PE-P1",
                "timestamp": $ts,
                "progress": $percent,
                "status": "Active",
                "impact_ready": false
              }' fmt-core-state.json > tmp.json && mv tmp.json fmt-core-state.json

      - name: Commit and Push
        run: |
          git config user.name "fmt-bot"
          git config user.email "bot@fmt.dev"
          git add fmt-core-state.json
          git diff --cached --quiet || git commit -m "Enhancer Tracker: Updated prediction progress"
          git push --force https://x-access-token:${{ secrets.PAT_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
