name: FMT Prediction Trigger (Live Execution)

on:
  workflow_dispatch:
    inputs:
      fixture:
        description: 'Enter fixture (e.g., Arsenal vs PSG)'
        required: true
      match_date:
        description: 'Enter match date (YYYY-MM-DD)'
        required: true

permissions:
  contents: write

jobs:
  run_fmt_prediction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Parse Fixture into Teams
        id: parse
        run: |
          FIXTURE="${{ github.event.inputs.fixture }}"
          TEAM_A=$(echo "$FIXTURE" | cut -d'v' -f1 | xargs)
          TEAM_B=$(echo "$FIXTURE" | cut -d'v' -f2 | xargs)
          echo "team_a=$TEAM_A" >> $GITHUB_OUTPUT
          echo "team_b=$TEAM_B" >> $GITHUB_OUTPUT

      - name: Inject FMT Request into JSON
        run: |
          DATE="${{ github.event.inputs.match_date }}"
          echo "🔧 Injecting FMT request into fmt-state.json..."
          jq --arg a "${{ steps.parse.outputs.team_a }}" \
             --arg b "${{ steps.parse.outputs.team_b }}" \
             --arg d "$DATE" \
             '.pending_fmt_request = {
                "team_a": $a,
                "team_b": $b,
                "date": $d,
                "source": "CommandHub",
                "trigger_id": "\($a | ascii_downcase | split(" ") | join("_"))_vs_\($b | ascii_downcase | split(" ") | join("_"))_\($d | gsub("-"; ""))"
              }' fmt-state.json > tmp.json && mv tmp.json fmt-state.json

      - name: Commit FMT Request
        run: |
          git config user.name "fmt-bot"
          git config user.email "bot@fmt.dev"
          git add fmt-state.json
          git commit -m "Inject pending FMT request: ${{ github.event.inputs.fixture }}"
          git push https://x-access-token:${{ secrets.PAT_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
