name: FMT Dev Tracker Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-dev-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for commit operations

      - name: Set up Git user
        run: |
          git config user.name "fmt-bot"
          git config user.email "fmt-bot@users.noreply.github.com"

      - name: Clean working directory before pull
        run: |
          git reset --hard
          git clean -fd

      - name: Pull latest changes
        run: git pull --rebase

      - name: Update commit log
        run: |
          # Example: append to a changelog file (replace this with your logic)
          echo "Update on $(date -u)" >> FMT_CHANGELOG.md

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore: update fmt-dev-tracker log [bot]"
          git push
        continue-on-error: true  # Prevent total failure if there's nothing to commit
