name: Patch Core Mount Logic

on:
  workflow_dispatch:

jobs:
  patch-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run patch script
        run: |
          echo "✅ Patching loader.py for split-state..."
          python vd-tools/promote_core_state.py
      - name: Commit and push
        run: |
          git config user.name "vd-patch-bot"
          git config user.email "vd-bot@fmt.dev"
          git add loader.py
          git commit -m "VD-36: Promote core_state_path in loader.py"
          git push || echo "No changes to commit"
